on:
  push:
    branches:
    - main
    - feature/*
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: spyoungtech/mirror-action@master
      with:
        REMOTE: git@gitlab.com:kxz/spring-boot-demo.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
        DEBUG: "true"
